pdos:
  RxScannerCommandRos: # This is command from HMI to PLC to control the scanner
    cob_id: 1076 # This is COB_ID 0x321 RPDO2 offset at 0x300 in PLC Node ID 0x21
    fields:
      - name: bServiceOpenScanner
        byte: 0
        bit: 0
        type: bool
      - name: bServiceCloseScanner
        byte: 1
        bit: 0
        type: bool
      - name: bPerformPreScan
        byte: 2
        bit: 0
        type: bool
      - name: bPerformPostScan
        byte: 3
        bit: 0
        type: bool
      - name: bStop
        byte: 4
        bit: 0
        type: bool
      - name: bRequestingOverrideMode
        byte: 5
        bit: 0
        type: bool
      - name: bRequestForceScannerPowerOn
        byte: 6
        bit: 0
        type: bool
      - name: bEnableScannerPower
        byte: 7
        bit: 0
        type: bool

  RxZeroCommand: # This is command from HMI to PLC to request zeroing of the scanner
    cob_id: 1932  
    fields:
      - name: gRx_byZeroRequest
        byte: 1
        type: byte #uint8