BASE_DIR: /mnt/c/work/projects/intelijet_v2
DATA_DIR: data
HMI_CMD_TOPIC: /hmi/cmd
PLC_CMD_TOPIC: /plc/cmd
SYSTEM_STATUS: /system_status
PRE_SCAN_TOPIC: /pre_scan_0
POST_SCAN_TOPIC: /post_scan_0
PRE_SCAN_CLOUD_TOPIC: /pre_scan_cloud
POST_SCAN_CLOUD_TOPIC: /post_scan_cloud
POST_SCAN_CLOUD_ALIGNED_TOPIC: /post_scan_cloud_aligned
CLOUD_COMPARED_TOPIC: /cloud_compared
ENCODER_JOINT_NAME: scanner_deploy_retract
ENCODER01_CAN_MSG: /encoder01/can_msg
ENCODER01_DATA: /encoder01/data
NOTIFICATION: notification
PLC_HEARTBEAT_MSG: /plc/heatbeat
active_lidar: lms511
blk360g2:
  pointcloud_topic: /blk360g2/pointcloud
  start_scan_service: /blk360g2/start_scan
  action_server_name: /blk360g2/start_scan
  goal_type: StartScanGoal
  scan_time_seconds: None
blkarc:
  pointcloud_topic: /blkarc/scan
  start_scan_service: /blkarc/start_scan
  action_server_name: /blkarc/timed_scan
  goal_type: TimedScanGoal
  scan_time_seconds: 10
lms511:
  pointcloud_topic: /lms511/scan
  start_scan_service: /lms511/start_scan
  action_server_name: /lms511/start_scan
  scan_time_seconds: None
crop_box:
  min:
    x: -1.0
    y: -5.0
    z: 0.2
  max:
    x: 7.0
    y: 5.0
    z: 8.0
housing_start_position: 12
housing_end_position: 135
encoder_length_at_zero_possition: 29910924
housing_open_speed_fast: 115
housing_open_speed_medium: 105
housing_open_speed_slow: 103
housing_close_speed_fast: 115
housing_close_speed_medium: 110
housing_close_speed_slow: 105
thickness:
  target: 30
  tolerance: 10
report:
  sitename: Jacon Equipment (test only)
  jobnumer: Jobnumber (test only)
  target: 30
  tolerance: 10
  thickness_avg: 0
  shotcrete_vol: 0
