#crop_pointcloud_by_box
crop_box:
  min:
    x: -1.0
    y: -5.0
    z: 0.2
  max:
    x: 7.0
    y: 5.0
    z: 8.0


# Start Housing possition in degree (start to collect data)
housing_start_position : 12 # value in degree (not in radian)
housing_end_position : 135 # value in degree (not in radian)
encoder_length_at_zero_possition: 29910924 # this value is readed from encoder when housing is at fully closed position

housing_open_speed_fast : 115 # speed in hz
housing_open_speed_medium : 105 # speed in hz
housing_open_speed_slow : 102 # speed in hz

housing_close_speed_fast : 110 # speed in hz
housing_close_speed_medium : 100 # speed in hz
housing_close_speed_slow : 100 # speed in hz

thickness:
  min: 0.01 # minimum thickness in meter
  max: 0.025  # maximum thickness in meter
