# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CaptureAnnotationsStub(object):
    """*
    Allows a client to write certain annotations to the current capture file.
    These methods can only be used while a capture is in progress.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginStaticPose = channel.unary_unary(
                '/api.blk.CaptureAnnotations/BeginStaticPose',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.EndStaticPose = channel.unary_unary(
                '/api.blk.CaptureAnnotations/EndStaticPose',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CaptureAnnotationsServicer(object):
    """*
    Allows a client to write certain annotations to the current capture file.
    These methods can only be used while a capture is in progress.
    """

    def BeginStaticPose(self, request, context):
        """*
        Marks the beginning of a static pose. The device must be scanning to be able to start the pose.

        Error Codes:
        - gRPC status 6 (ALREADY_EXISTS): If a static pose is already in progress.
        - gRPC status 9 (FAILED_PRECONDITION): If the device is not in a capture.
        - gRPC status 14 (UNAVAILABLE): If the static pose cannot be started for any other reason. This may be a transient condition and can be retried.

        Authorization Scopes:
        - `capture`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndStaticPose(self, request, context):
        """*
        Marks the end of a static pose. The caller is responsible for calling this method before starting to move again.

        Error Codes:
        - gRPC status 9 (FAILED_PRECONDITION): If no static pose had previously begun or the device is not currently in a capture.

        Authorization Scopes:
        - `capture`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptureAnnotationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginStaticPose': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginStaticPose,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'EndStaticPose': grpc.unary_unary_rpc_method_handler(
                    servicer.EndStaticPose,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.blk.CaptureAnnotations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CaptureAnnotations(object):
    """*
    Allows a client to write certain annotations to the current capture file.
    These methods can only be used while a capture is in progress.
    """

    @staticmethod
    def BeginStaticPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.blk.CaptureAnnotations/BeginStaticPose',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndStaticPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.blk.CaptureAnnotations/EndStaticPose',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
