# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/capture_annotations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/capture_annotations.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&blk_arc_grpc/capture_annotations.proto\x12\x07\x61pi.blk\x1a\x1bgoogle/protobuf/empty.proto2\x98\x01\n\x12\x43\x61ptureAnnotations\x12\x41\n\x0f\x42\x65ginStaticPose\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n\rEndStaticPose\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CAPTUREANNOTATIONS = _descriptor.ServiceDescriptor(
  name='CaptureAnnotations',
  full_name='api.blk.CaptureAnnotations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=233,
  methods=[
  _descriptor.MethodDescriptor(
    name='BeginStaticPose',
    full_name='api.blk.CaptureAnnotations.BeginStaticPose',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndStaticPose',
    full_name='api.blk.CaptureAnnotations.EndStaticPose',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAPTUREANNOTATIONS)

DESCRIPTOR.services_by_name['CaptureAnnotations'] = _CAPTUREANNOTATIONS

# @@protoc_insertion_point(module_scope)
