# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/clock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/clock.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x62lk_arc_grpc/clock.proto\x12\x07\x61pi.blk\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n\x12TimestampsResponse\x12,\n\tmain_fpga\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x36\n\x13head_assembly_clock\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12/\n\x0bsystem_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2R\n\x05\x43lock\x12I\n\x12GetCurrentDateTime\x12\x16.google.protobuf.Empty\x1a\x1b.api.blk.TimestampsResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TIMESTAMPSRESPONSE = _descriptor.Descriptor(
  name='TimestampsResponse',
  full_name='api.blk.TimestampsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_fpga', full_name='api.blk.TimestampsResponse.main_fpga', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_assembly_clock', full_name='api.blk.TimestampsResponse.head_assembly_clock', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_time', full_name='api.blk.TimestampsResponse.system_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=303,
)

_TIMESTAMPSRESPONSE.fields_by_name['main_fpga'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_TIMESTAMPSRESPONSE.fields_by_name['head_assembly_clock'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_TIMESTAMPSRESPONSE.fields_by_name['system_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['TimestampsResponse'] = _TIMESTAMPSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampsResponse = _reflection.GeneratedProtocolMessageType('TimestampsResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPSRESPONSE,
  '__module__' : 'blk_arc_grpc.clock_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.TimestampsResponse)
  })
_sym_db.RegisterMessage(TimestampsResponse)



_CLOCK = _descriptor.ServiceDescriptor(
  name='Clock',
  full_name='api.blk.Clock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=305,
  serialized_end=387,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCurrentDateTime',
    full_name='api.blk.Clock.GetCurrentDateTime',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TIMESTAMPSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOCK)

DESCRIPTOR.services_by_name['Clock'] = _CLOCK

# @@protoc_insertion_point(module_scope)
