# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from blk_arc_grpc import coordinate_frames_pb2 as blk__arc__grpc_dot_coordinate__frames__pb2


class CoordinateFramesStub(object):
    """*
    Provides information about how the coordinate systems / frames
    of different sensors are located and aligned.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransformationData = channel.unary_unary(
                '/api.blk.CoordinateFrames/GetTransformationData',
                request_serializer=blk__arc__grpc_dot_coordinate__frames__pb2.TransformationRequest.SerializeToString,
                response_deserializer=blk__arc__grpc_dot_coordinate__frames__pb2.AlignedExtrinsics.FromString,
                )


class CoordinateFramesServicer(object):
    """*
    Provides information about how the coordinate systems / frames
    of different sensors are located and aligned.
    """

    def GetTransformationData(self, request, context):
        """*
        Get the current set transformation data.

        Authorization Scopes:
        - `calibration.transform`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinateFramesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransformationData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransformationData,
                    request_deserializer=blk__arc__grpc_dot_coordinate__frames__pb2.TransformationRequest.FromString,
                    response_serializer=blk__arc__grpc_dot_coordinate__frames__pb2.AlignedExtrinsics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.blk.CoordinateFrames', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoordinateFrames(object):
    """*
    Provides information about how the coordinate systems / frames
    of different sensors are located and aligned.
    """

    @staticmethod
    def GetTransformationData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.blk.CoordinateFrames/GetTransformationData',
            blk__arc__grpc_dot_coordinate__frames__pb2.TransformationRequest.SerializeToString,
            blk__arc__grpc_dot_coordinate__frames__pb2.AlignedExtrinsics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
