# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/coordinate_frames.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/coordinate_frames.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$blk_arc_grpc/coordinate_frames.proto\x12\x07\x61pi.blk\"&\n\x12SensorAffineMatrix\x12\x10\n\x08\x65lements\x18\x01 \x03(\x01\"\x9b\x03\n\x11\x41lignedExtrinsics\x12\x42\n\x1dslam_cam_front_transformation\x18\x01 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\x12\x41\n\x1cslam_cam_left_transformation\x18\x02 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\x12\x42\n\x1dslam_cam_right_transformation\x18\x03 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\x12<\n\x17user_cam_transformation\x18\x04 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\x12\x37\n\x12imu_transformation\x18\x05 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\x12\x44\n\x1fhousing_ref_mark_transformation\x18\x06 \x01(\x0b\x32\x1b.api.blk.SensorAffineMatrix\"\x17\n\x15TransformationRequest2g\n\x10\x43oordinateFrames\x12S\n\x15GetTransformationData\x12\x1e.api.blk.TransformationRequest\x1a\x1a.api.blk.AlignedExtrinsicsb\x06proto3'
)




_SENSORAFFINEMATRIX = _descriptor.Descriptor(
  name='SensorAffineMatrix',
  full_name='api.blk.SensorAffineMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='api.blk.SensorAffineMatrix.elements', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=87,
)


_ALIGNEDEXTRINSICS = _descriptor.Descriptor(
  name='AlignedExtrinsics',
  full_name='api.blk.AlignedExtrinsics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slam_cam_front_transformation', full_name='api.blk.AlignedExtrinsics.slam_cam_front_transformation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slam_cam_left_transformation', full_name='api.blk.AlignedExtrinsics.slam_cam_left_transformation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slam_cam_right_transformation', full_name='api.blk.AlignedExtrinsics.slam_cam_right_transformation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_cam_transformation', full_name='api.blk.AlignedExtrinsics.user_cam_transformation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_transformation', full_name='api.blk.AlignedExtrinsics.imu_transformation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='housing_ref_mark_transformation', full_name='api.blk.AlignedExtrinsics.housing_ref_mark_transformation', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=501,
)


_TRANSFORMATIONREQUEST = _descriptor.Descriptor(
  name='TransformationRequest',
  full_name='api.blk.TransformationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=526,
)

_ALIGNEDEXTRINSICS.fields_by_name['slam_cam_front_transformation'].message_type = _SENSORAFFINEMATRIX
_ALIGNEDEXTRINSICS.fields_by_name['slam_cam_left_transformation'].message_type = _SENSORAFFINEMATRIX
_ALIGNEDEXTRINSICS.fields_by_name['slam_cam_right_transformation'].message_type = _SENSORAFFINEMATRIX
_ALIGNEDEXTRINSICS.fields_by_name['user_cam_transformation'].message_type = _SENSORAFFINEMATRIX
_ALIGNEDEXTRINSICS.fields_by_name['imu_transformation'].message_type = _SENSORAFFINEMATRIX
_ALIGNEDEXTRINSICS.fields_by_name['housing_ref_mark_transformation'].message_type = _SENSORAFFINEMATRIX
DESCRIPTOR.message_types_by_name['SensorAffineMatrix'] = _SENSORAFFINEMATRIX
DESCRIPTOR.message_types_by_name['AlignedExtrinsics'] = _ALIGNEDEXTRINSICS
DESCRIPTOR.message_types_by_name['TransformationRequest'] = _TRANSFORMATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorAffineMatrix = _reflection.GeneratedProtocolMessageType('SensorAffineMatrix', (_message.Message,), {
  'DESCRIPTOR' : _SENSORAFFINEMATRIX,
  '__module__' : 'blk_arc_grpc.coordinate_frames_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.SensorAffineMatrix)
  })
_sym_db.RegisterMessage(SensorAffineMatrix)

AlignedExtrinsics = _reflection.GeneratedProtocolMessageType('AlignedExtrinsics', (_message.Message,), {
  'DESCRIPTOR' : _ALIGNEDEXTRINSICS,
  '__module__' : 'blk_arc_grpc.coordinate_frames_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.AlignedExtrinsics)
  })
_sym_db.RegisterMessage(AlignedExtrinsics)

TransformationRequest = _reflection.GeneratedProtocolMessageType('TransformationRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMATIONREQUEST,
  '__module__' : 'blk_arc_grpc.coordinate_frames_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.TransformationRequest)
  })
_sym_db.RegisterMessage(TransformationRequest)



_COORDINATEFRAMES = _descriptor.ServiceDescriptor(
  name='CoordinateFrames',
  full_name='api.blk.CoordinateFrames',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=528,
  serialized_end=631,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTransformationData',
    full_name='api.blk.CoordinateFrames.GetTransformationData',
    index=0,
    containing_service=None,
    input_type=_TRANSFORMATIONREQUEST,
    output_type=_ALIGNEDEXTRINSICS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATEFRAMES)

DESCRIPTOR.services_by_name['CoordinateFrames'] = _COORDINATEFRAMES

# @@protoc_insertion_point(module_scope)
