# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/device.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x62lk_arc_grpc/device.proto\x12\x07\x61pi.blk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x03\n\x13\x44\x65viceStateResponse\x12\x31\n\x05state\x18\x01 \x01(\x0e\x32\".api.blk.DeviceStateResponse.State\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0estate_progress\x18\x03 \x01(\x02\x12\x15\n\rstate_details\x18\x04 \x01(\t\"\xa8\x02\n\x05State\x12\x0b\n\x07\x42OOTING\x10\x00\x12\x13\n\x0fOTA_IN_PROGRESS\x10\x01\x12\x14\n\x10\x46LASHING_HW_MAIN\x10\x02\x12\x14\n\x10\x46LASHING_HW_HEAD\x10\x03\x12\x08\n\x04IDLE\x10\x04\x12\x14\n\x10\x43\x41PTURE_STARTING\x10\x05\x12\x13\n\x0f\x43\x41PTURE_RUNNING\x10\x06\x12\x1a\n\x16\x43\x41PTURE_RUNNING_STATIC\x10\x0c\x12\x14\n\x10\x43\x41PTURE_STOPPING\x10\x07\x12\x10\n\x0c\x46\x41ULT_BROKEN\x10\x08\x12\x12\n\x0e\x46\x41ULT_DEGRADED\x10\t\x12\x1e\n\x1a\x46\x41ULT_RECOVERABLE_DEGRADED\x10\n\x12\x0c\n\x08SHUTDOWN\x10\x0b\x12\x16\n\x12SELF_CHECK_RUNNING\x10\r2\x9a\x01\n\x06\x44\x65vice\x12\x43\n\x0b\x44\x65viceState\x12\x16.google.protobuf.Empty\x1a\x1c.api.blk.DeviceStateResponse\x12K\n\x11\x44\x65viceStateStream\x12\x16.google.protobuf.Empty\x1a\x1c.api.blk.DeviceStateResponse0\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_DEVICESTATERESPONSE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='api.blk.DeviceStateResponse.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOOTING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTA_IN_PROGRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLASHING_HW_MAIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLASHING_HW_HEAD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAPTURE_STARTING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAPTURE_RUNNING', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAPTURE_RUNNING_STATIC', index=7, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAPTURE_STOPPING', index=8, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAULT_BROKEN', index=9, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAULT_DEGRADED', index=10, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAULT_RECOVERABLE_DEGRADED', index=11, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN', index=12, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELF_CHECK_RUNNING', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=270,
  serialized_end=566,
)
_sym_db.RegisterEnumDescriptor(_DEVICESTATERESPONSE_STATE)


_DEVICESTATERESPONSE = _descriptor.Descriptor(
  name='DeviceStateResponse',
  full_name='api.blk.DeviceStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='api.blk.DeviceStateResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='api.blk.DeviceStateResponse.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state_progress', full_name='api.blk.DeviceStateResponse.state_progress', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state_details', full_name='api.blk.DeviceStateResponse.state_details', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEVICESTATERESPONSE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=566,
)

_DEVICESTATERESPONSE.fields_by_name['state'].enum_type = _DEVICESTATERESPONSE_STATE
_DEVICESTATERESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DEVICESTATERESPONSE_STATE.containing_type = _DEVICESTATERESPONSE
DESCRIPTOR.message_types_by_name['DeviceStateResponse'] = _DEVICESTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceStateResponse = _reflection.GeneratedProtocolMessageType('DeviceStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTATERESPONSE,
  '__module__' : 'blk_arc_grpc.device_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.DeviceStateResponse)
  })
_sym_db.RegisterMessage(DeviceStateResponse)



_DEVICE = _descriptor.ServiceDescriptor(
  name='Device',
  full_name='api.blk.Device',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=569,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeviceState',
    full_name='api.blk.Device.DeviceState',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DEVICESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeviceStateStream',
    full_name='api.blk.Device.DeviceStateStream',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DEVICESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICE)

DESCRIPTOR.services_by_name['Device'] = _DEVICE

# @@protoc_insertion_point(module_scope)
