# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/fault.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/fault.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x62lk_arc_grpc/fault.proto\x12\x07\x61pi.blk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xce\x04\n\x0b\x46\x61ultReport\x12\x11\n\treport_id\x18\x01 \x01(\r\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\r\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x32\n\x0eraised_at_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x45\n\x14required_user_action\x18\x06 \x01(\x0e\x32\'.api.blk.FaultReport.RequiredUserAction\x12:\n\x0e\x66\x61ult_severity\x18\x07 \x01(\x0e\x32\".api.blk.FaultReport.SeverityLevel\"\xf1\x01\n\x12RequiredUserAction\x12\x12\n\x0eUNKNOWN_ACTION\x10\x00\x12\x12\n\x0eNONE_SPECIFIED\x10\x01\x12\r\n\tNO_ACTION\x10\x02\x12\x0e\n\nRETRY_SCAN\x10\x03\x12\x0f\n\x0b\x41\x43KNOWLEDGE\x10\x04\x12\x11\n\rREBOOT_DEVICE\x10\x05\x12\x13\n\x0f\x43ONTACT_SUPPORT\x10\x06\x12\x13\n\x0fLET_DEVICE_COOL\x10\x07\x12\x15\n\x11\x46REE_DEVICE_SPACE\x10\x08\x12\x13\n\x0fREPLACE_BATTERY\x10\t\x12\x1a\n\x16\x43LEAN_BATTERY_CONTACTS\x10\n\"P\n\rSeverityLevel\x12\n\n\x06\x42ROKEN\x10\x00\x12\x0c\n\x08\x44\x45GRADED\x10\x01\x12\x18\n\x14RECOVERABLE_DEGRADED\x10\x02\x12\x0b\n\x07WARNING\x10\x03\"W\n\x17\x41\x63knowledgeFaultRequest\x12\x10\n\x08location\x18\x01 \x01(\t\x12*\n\x04\x63ode\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"7\n\x0f\x46\x61ultReportList\x12$\n\x06\x66\x61ults\x18\x01 \x03(\x0b\x32\x14.api.blk.FaultReport2\xde\x01\n\x05\x46\x61ult\x12\x42\n\x0eGetFaultReport\x12\x16.google.protobuf.Empty\x1a\x18.api.blk.FaultReportList\x12\x43\n\x11StreamFaultReport\x12\x16.google.protobuf.Empty\x1a\x14.api.blk.FaultReport0\x01\x12L\n\x10\x41\x63knowledgeFault\x12 .api.blk.AcknowledgeFaultRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])



_FAULTREPORT_REQUIREDUSERACTION = _descriptor.EnumDescriptor(
  name='RequiredUserAction',
  full_name='api.blk.FaultReport.RequiredUserAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ACTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NONE_SPECIFIED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_ACTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETRY_SCAN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACKNOWLEDGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_DEVICE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTACT_SUPPORT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LET_DEVICE_COOL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FREE_DEVICE_SPACE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPLACE_BATTERY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLEAN_BATTERY_CONTACTS', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=399,
  serialized_end=640,
)
_sym_db.RegisterEnumDescriptor(_FAULTREPORT_REQUIREDUSERACTION)

_FAULTREPORT_SEVERITYLEVEL = _descriptor.EnumDescriptor(
  name='SeverityLevel',
  full_name='api.blk.FaultReport.SeverityLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BROKEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEGRADED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECOVERABLE_DEGRADED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=642,
  serialized_end=722,
)
_sym_db.RegisterEnumDescriptor(_FAULTREPORT_SEVERITYLEVEL)


_FAULTREPORT = _descriptor.Descriptor(
  name='FaultReport',
  full_name='api.blk.FaultReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='report_id', full_name='api.blk.FaultReport.report_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='api.blk.FaultReport.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='api.blk.FaultReport.code', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='api.blk.FaultReport.details', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raised_at_time', full_name='api.blk.FaultReport.raised_at_time', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='required_user_action', full_name='api.blk.FaultReport.required_user_action', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fault_severity', full_name='api.blk.FaultReport.fault_severity', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FAULTREPORT_REQUIREDUSERACTION,
    _FAULTREPORT_SEVERITYLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=722,
)


_ACKNOWLEDGEFAULTREQUEST = _descriptor.Descriptor(
  name='AcknowledgeFaultRequest',
  full_name='api.blk.AcknowledgeFaultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='api.blk.AcknowledgeFaultRequest.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='api.blk.AcknowledgeFaultRequest.code', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=811,
)


_FAULTREPORTLIST = _descriptor.Descriptor(
  name='FaultReportList',
  full_name='api.blk.FaultReportList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faults', full_name='api.blk.FaultReportList.faults', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=813,
  serialized_end=868,
)

_FAULTREPORT.fields_by_name['raised_at_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FAULTREPORT.fields_by_name['required_user_action'].enum_type = _FAULTREPORT_REQUIREDUSERACTION
_FAULTREPORT.fields_by_name['fault_severity'].enum_type = _FAULTREPORT_SEVERITYLEVEL
_FAULTREPORT_REQUIREDUSERACTION.containing_type = _FAULTREPORT
_FAULTREPORT_SEVERITYLEVEL.containing_type = _FAULTREPORT
_ACKNOWLEDGEFAULTREQUEST.fields_by_name['code'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_FAULTREPORTLIST.fields_by_name['faults'].message_type = _FAULTREPORT
DESCRIPTOR.message_types_by_name['FaultReport'] = _FAULTREPORT
DESCRIPTOR.message_types_by_name['AcknowledgeFaultRequest'] = _ACKNOWLEDGEFAULTREQUEST
DESCRIPTOR.message_types_by_name['FaultReportList'] = _FAULTREPORTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaultReport = _reflection.GeneratedProtocolMessageType('FaultReport', (_message.Message,), {
  'DESCRIPTOR' : _FAULTREPORT,
  '__module__' : 'blk_arc_grpc.fault_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.FaultReport)
  })
_sym_db.RegisterMessage(FaultReport)

AcknowledgeFaultRequest = _reflection.GeneratedProtocolMessageType('AcknowledgeFaultRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACKNOWLEDGEFAULTREQUEST,
  '__module__' : 'blk_arc_grpc.fault_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.AcknowledgeFaultRequest)
  })
_sym_db.RegisterMessage(AcknowledgeFaultRequest)

FaultReportList = _reflection.GeneratedProtocolMessageType('FaultReportList', (_message.Message,), {
  'DESCRIPTOR' : _FAULTREPORTLIST,
  '__module__' : 'blk_arc_grpc.fault_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.FaultReportList)
  })
_sym_db.RegisterMessage(FaultReportList)



_FAULT = _descriptor.ServiceDescriptor(
  name='Fault',
  full_name='api.blk.Fault',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=871,
  serialized_end=1093,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFaultReport',
    full_name='api.blk.Fault.GetFaultReport',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FAULTREPORTLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamFaultReport',
    full_name='api.blk.Fault.StreamFaultReport',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FAULTREPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AcknowledgeFault',
    full_name='api.blk.Fault.AcknowledgeFault',
    index=2,
    containing_service=None,
    input_type=_ACKNOWLEDGEFAULTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAULT)

DESCRIPTOR.services_by_name['Fault'] = _FAULT

# @@protoc_insertion_point(module_scope)
