# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/masking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/masking.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x62lk_arc_grpc/masking.proto\x12\x07\x61pi.blk\"g\n\x07\x42itMask\x12\x1a\n\x12image_width_pixels\x18\x01 \x01(\x04\x12\x1b\n\x13image_height_pixels\x18\x02 \x01(\x04\x12\x15\n\rbytes_per_row\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"7\n\x08\x42yteMask\x12\r\n\x05width\x18\x01 \x01(\x04\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"4\n\x0eSLAMCameraMask\x12\"\n\x08\x62it_mask\x18\x02 \x01(\x0b\x32\x10.api.blk.BitMask\"1\n\tLidarMask\x12$\n\tbyte_mask\x18\x01 \x01(\x0b\x32\x11.api.blk.ByteMask\"\x96\x01\n\x0fMaskDescription\x12#\n\x02id\x18\x01 \x01(\x0e\x32\x17.api.blk.MaskIdentifier\x12,\n\tslam_mask\x18\x02 \x01(\x0b\x32\x17.api.blk.SLAMCameraMaskH\x00\x12(\n\nlidar_mask\x18\x03 \x01(\x0b\x32\x12.api.blk.LidarMaskH\x00\x42\x06\n\x04mask\"2\n\x0bMaskRequest\x12#\n\x02id\x18\x01 \x01(\x0e\x32\x17.api.blk.MaskIdentifier\"\x11\n\x0fMaskSetResponse\"\x13\n\x11MaskResetResponse*p\n\x0eMaskIdentifier\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\t\n\x05LIDAR\x10\x01\x12\x14\n\x10SLAM_CAMERA_LEFT\x10\x02\x12\x16\n\x12SLAM_CAMERA_CENTER\x10\x03\x12\x15\n\x11SLAM_CAMERA_RIGHT\x10\x04\x32\xc2\x01\n\x07Masking\x12=\n\tResetMask\x12\x14.api.blk.MaskRequest\x1a\x1a.api.blk.MaskResetResponse\x12\x39\n\x07GetMask\x12\x14.api.blk.MaskRequest\x1a\x18.api.blk.MaskDescription\x12=\n\x07SetMask\x12\x18.api.blk.MaskDescription\x1a\x18.api.blk.MaskSetResponseb\x06proto3'
)

_MASKIDENTIFIER = _descriptor.EnumDescriptor(
  name='MaskIdentifier',
  full_name='api.blk.MaskIdentifier',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIDAR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SLAM_CAMERA_LEFT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SLAM_CAMERA_CENTER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SLAM_CAMERA_RIGHT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=551,
  serialized_end=663,
)
_sym_db.RegisterEnumDescriptor(_MASKIDENTIFIER)

MaskIdentifier = enum_type_wrapper.EnumTypeWrapper(_MASKIDENTIFIER)
TYPE_UNSET = 0
LIDAR = 1
SLAM_CAMERA_LEFT = 2
SLAM_CAMERA_CENTER = 3
SLAM_CAMERA_RIGHT = 4



_BITMASK = _descriptor.Descriptor(
  name='BitMask',
  full_name='api.blk.BitMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_width_pixels', full_name='api.blk.BitMask.image_width_pixels', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_height_pixels', full_name='api.blk.BitMask.image_height_pixels', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_per_row', full_name='api.blk.BitMask.bytes_per_row', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='api.blk.BitMask.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=142,
)


_BYTEMASK = _descriptor.Descriptor(
  name='ByteMask',
  full_name='api.blk.ByteMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='api.blk.ByteMask.width', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='api.blk.ByteMask.height', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='api.blk.ByteMask.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=199,
)


_SLAMCAMERAMASK = _descriptor.Descriptor(
  name='SLAMCameraMask',
  full_name='api.blk.SLAMCameraMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bit_mask', full_name='api.blk.SLAMCameraMask.bit_mask', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=253,
)


_LIDARMASK = _descriptor.Descriptor(
  name='LidarMask',
  full_name='api.blk.LidarMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_mask', full_name='api.blk.LidarMask.byte_mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=304,
)


_MASKDESCRIPTION = _descriptor.Descriptor(
  name='MaskDescription',
  full_name='api.blk.MaskDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.blk.MaskDescription.id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slam_mask', full_name='api.blk.MaskDescription.slam_mask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidar_mask', full_name='api.blk.MaskDescription.lidar_mask', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='mask', full_name='api.blk.MaskDescription.mask',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=307,
  serialized_end=457,
)


_MASKREQUEST = _descriptor.Descriptor(
  name='MaskRequest',
  full_name='api.blk.MaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.blk.MaskRequest.id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=509,
)


_MASKSETRESPONSE = _descriptor.Descriptor(
  name='MaskSetResponse',
  full_name='api.blk.MaskSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=528,
)


_MASKRESETRESPONSE = _descriptor.Descriptor(
  name='MaskResetResponse',
  full_name='api.blk.MaskResetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=549,
)

_SLAMCAMERAMASK.fields_by_name['bit_mask'].message_type = _BITMASK
_LIDARMASK.fields_by_name['byte_mask'].message_type = _BYTEMASK
_MASKDESCRIPTION.fields_by_name['id'].enum_type = _MASKIDENTIFIER
_MASKDESCRIPTION.fields_by_name['slam_mask'].message_type = _SLAMCAMERAMASK
_MASKDESCRIPTION.fields_by_name['lidar_mask'].message_type = _LIDARMASK
_MASKDESCRIPTION.oneofs_by_name['mask'].fields.append(
  _MASKDESCRIPTION.fields_by_name['slam_mask'])
_MASKDESCRIPTION.fields_by_name['slam_mask'].containing_oneof = _MASKDESCRIPTION.oneofs_by_name['mask']
_MASKDESCRIPTION.oneofs_by_name['mask'].fields.append(
  _MASKDESCRIPTION.fields_by_name['lidar_mask'])
_MASKDESCRIPTION.fields_by_name['lidar_mask'].containing_oneof = _MASKDESCRIPTION.oneofs_by_name['mask']
_MASKREQUEST.fields_by_name['id'].enum_type = _MASKIDENTIFIER
DESCRIPTOR.message_types_by_name['BitMask'] = _BITMASK
DESCRIPTOR.message_types_by_name['ByteMask'] = _BYTEMASK
DESCRIPTOR.message_types_by_name['SLAMCameraMask'] = _SLAMCAMERAMASK
DESCRIPTOR.message_types_by_name['LidarMask'] = _LIDARMASK
DESCRIPTOR.message_types_by_name['MaskDescription'] = _MASKDESCRIPTION
DESCRIPTOR.message_types_by_name['MaskRequest'] = _MASKREQUEST
DESCRIPTOR.message_types_by_name['MaskSetResponse'] = _MASKSETRESPONSE
DESCRIPTOR.message_types_by_name['MaskResetResponse'] = _MASKRESETRESPONSE
DESCRIPTOR.enum_types_by_name['MaskIdentifier'] = _MASKIDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitMask = _reflection.GeneratedProtocolMessageType('BitMask', (_message.Message,), {
  'DESCRIPTOR' : _BITMASK,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.BitMask)
  })
_sym_db.RegisterMessage(BitMask)

ByteMask = _reflection.GeneratedProtocolMessageType('ByteMask', (_message.Message,), {
  'DESCRIPTOR' : _BYTEMASK,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.ByteMask)
  })
_sym_db.RegisterMessage(ByteMask)

SLAMCameraMask = _reflection.GeneratedProtocolMessageType('SLAMCameraMask', (_message.Message,), {
  'DESCRIPTOR' : _SLAMCAMERAMASK,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.SLAMCameraMask)
  })
_sym_db.RegisterMessage(SLAMCameraMask)

LidarMask = _reflection.GeneratedProtocolMessageType('LidarMask', (_message.Message,), {
  'DESCRIPTOR' : _LIDARMASK,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.LidarMask)
  })
_sym_db.RegisterMessage(LidarMask)

MaskDescription = _reflection.GeneratedProtocolMessageType('MaskDescription', (_message.Message,), {
  'DESCRIPTOR' : _MASKDESCRIPTION,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.MaskDescription)
  })
_sym_db.RegisterMessage(MaskDescription)

MaskRequest = _reflection.GeneratedProtocolMessageType('MaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _MASKREQUEST,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.MaskRequest)
  })
_sym_db.RegisterMessage(MaskRequest)

MaskSetResponse = _reflection.GeneratedProtocolMessageType('MaskSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _MASKSETRESPONSE,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.MaskSetResponse)
  })
_sym_db.RegisterMessage(MaskSetResponse)

MaskResetResponse = _reflection.GeneratedProtocolMessageType('MaskResetResponse', (_message.Message,), {
  'DESCRIPTOR' : _MASKRESETRESPONSE,
  '__module__' : 'blk_arc_grpc.masking_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.MaskResetResponse)
  })
_sym_db.RegisterMessage(MaskResetResponse)



_MASKING = _descriptor.ServiceDescriptor(
  name='Masking',
  full_name='api.blk.Masking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=666,
  serialized_end=860,
  methods=[
  _descriptor.MethodDescriptor(
    name='ResetMask',
    full_name='api.blk.Masking.ResetMask',
    index=0,
    containing_service=None,
    input_type=_MASKREQUEST,
    output_type=_MASKRESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMask',
    full_name='api.blk.Masking.GetMask',
    index=1,
    containing_service=None,
    input_type=_MASKREQUEST,
    output_type=_MASKDESCRIPTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetMask',
    full_name='api.blk.Masking.SetMask',
    index=2,
    containing_service=None,
    input_type=_MASKDESCRIPTION,
    output_type=_MASKSETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASKING)

DESCRIPTOR.services_by_name['Masking'] = _MASKING

# @@protoc_insertion_point(module_scope)
