# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from blk_arc_grpc import power_pb2 as blk__arc__grpc_dot_power__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PowerStub(object):
    """*
    Allows a user to retrieve information about the current power source of the BLK device.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPowerStatus = channel.unary_unary(
                '/api.blk.Power/GetPowerStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=blk__arc__grpc_dot_power__pb2.PowerStatusResponse.FromString,
                )


class PowerServicer(object):
    """*
    Allows a user to retrieve information about the current power source of the BLK device.
    """

    def GetPowerStatus(self, request, context):
        """*
        Gets information about the power source and the battery level if applicable.

        Authorization Scopes:
        - `info`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPowerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowerStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=blk__arc__grpc_dot_power__pb2.PowerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.blk.Power', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Power(object):
    """*
    Allows a user to retrieve information about the current power source of the BLK device.
    """

    @staticmethod
    def GetPowerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.blk.Power/GetPowerStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            blk__arc__grpc_dot_power__pb2.PowerStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
