# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/power.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/power.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x62lk_arc_grpc/power.proto\x12\x07\x61pi.blk\x1a\x1bgoogle/protobuf/empty.proto\"\xca\x02\n\x13PowerStatusResponse\x12 \n\x18\x62\x61ttery_level_in_percent\x18\x01 \x01(\x02\x12@\n\rbattery_alert\x18\x02 \x01(\x0e\x32).api.blk.PowerStatusResponse.BatteryAlert\x12>\n\x0cpower_source\x18\x03 \x01(\x0e\x32(.api.blk.PowerStatusResponse.PowerSource\"O\n\x0c\x42\x61tteryAlert\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nBATTERY_OK\x10\x01\x12\x0f\n\x0b\x42\x41TTERY_LOW\x10\x02\x12\x14\n\x10\x42\x41TTERY_CRITICAL\x10\x03\">\n\x0bPowerSource\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x42\x41TTERY\x10\x01\x12\x0c\n\x08\x45XTERNAL\x10\x02\x12\x07\n\x03USB\x10\x03\x32O\n\x05Power\x12\x46\n\x0eGetPowerStatus\x12\x16.google.protobuf.Empty\x1a\x1c.api.blk.PowerStatusResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_POWERSTATUSRESPONSE_BATTERYALERT = _descriptor.EnumDescriptor(
  name='BatteryAlert',
  full_name='api.blk.PowerStatusResponse.BatteryAlert',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_LOW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_CRITICAL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=254,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_POWERSTATUSRESPONSE_BATTERYALERT)

_POWERSTATUSRESPONSE_POWERSOURCE = _descriptor.EnumDescriptor(
  name='PowerSource',
  full_name='api.blk.PowerStatusResponse.PowerSource',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USB', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=335,
  serialized_end=397,
)
_sym_db.RegisterEnumDescriptor(_POWERSTATUSRESPONSE_POWERSOURCE)


_POWERSTATUSRESPONSE = _descriptor.Descriptor(
  name='PowerStatusResponse',
  full_name='api.blk.PowerStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='battery_level_in_percent', full_name='api.blk.PowerStatusResponse.battery_level_in_percent', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_alert', full_name='api.blk.PowerStatusResponse.battery_alert', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_source', full_name='api.blk.PowerStatusResponse.power_source', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POWERSTATUSRESPONSE_BATTERYALERT,
    _POWERSTATUSRESPONSE_POWERSOURCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=397,
)

_POWERSTATUSRESPONSE.fields_by_name['battery_alert'].enum_type = _POWERSTATUSRESPONSE_BATTERYALERT
_POWERSTATUSRESPONSE.fields_by_name['power_source'].enum_type = _POWERSTATUSRESPONSE_POWERSOURCE
_POWERSTATUSRESPONSE_BATTERYALERT.containing_type = _POWERSTATUSRESPONSE
_POWERSTATUSRESPONSE_POWERSOURCE.containing_type = _POWERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['PowerStatusResponse'] = _POWERSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerStatusResponse = _reflection.GeneratedProtocolMessageType('PowerStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _POWERSTATUSRESPONSE,
  '__module__' : 'blk_arc_grpc.power_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.PowerStatusResponse)
  })
_sym_db.RegisterMessage(PowerStatusResponse)



_POWER = _descriptor.ServiceDescriptor(
  name='Power',
  full_name='api.blk.Power',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPowerStatus',
    full_name='api.blk.Power.GetPowerStatus',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_POWERSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POWER)

DESCRIPTOR.services_by_name['Power'] = _POWER

# @@protoc_insertion_point(module_scope)
