# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blk_arc_grpc/system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blk_arc_grpc/system.proto',
  package='api.blk',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x62lk_arc_grpc/system.proto\x12\x07\x61pi.blk\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n\x12\x43ountryCodeRequest\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\"E\n\x10TimestampRequest\x12\x31\n\rutc_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x8e\x03\n\x06System\x12\x43\n\rGetSystemTime\x12\x16.google.protobuf.Empty\x1a\x1a.google.protobuf.Timestamp\x12\x42\n\rSetSystemTime\x12\x19.api.blk.TimestampRequest\x1a\x16.google.protobuf.Empty\x12\x45\n\x0eSetCountryCode\x12\x1b.api.blk.CountryCodeRequest\x1a\x16.google.protobuf.Empty\x12>\n\tGetUptime\x12\x16.google.protobuf.Empty\x1a\x19.google.protobuf.Duration\x12\x38\n\x06Reboot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x08Shutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_COUNTRYCODEREQUEST = _descriptor.Descriptor(
  name='CountryCodeRequest',
  full_name='api.blk.CountryCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_code', full_name='api.blk.CountryCodeRequest.country_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=174,
)


_TIMESTAMPREQUEST = _descriptor.Descriptor(
  name='TimestampRequest',
  full_name='api.blk.TimestampRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utc_timestamp', full_name='api.blk.TimestampRequest.utc_timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=245,
)

_TIMESTAMPREQUEST.fields_by_name['utc_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['CountryCodeRequest'] = _COUNTRYCODEREQUEST
DESCRIPTOR.message_types_by_name['TimestampRequest'] = _TIMESTAMPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryCodeRequest = _reflection.GeneratedProtocolMessageType('CountryCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYCODEREQUEST,
  '__module__' : 'blk_arc_grpc.system_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.CountryCodeRequest)
  })
_sym_db.RegisterMessage(CountryCodeRequest)

TimestampRequest = _reflection.GeneratedProtocolMessageType('TimestampRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPREQUEST,
  '__module__' : 'blk_arc_grpc.system_pb2'
  # @@protoc_insertion_point(class_scope:api.blk.TimestampRequest)
  })
_sym_db.RegisterMessage(TimestampRequest)



_SYSTEM = _descriptor.ServiceDescriptor(
  name='System',
  full_name='api.blk.System',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=248,
  serialized_end=646,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSystemTime',
    full_name='api.blk.System.GetSystemTime',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetSystemTime',
    full_name='api.blk.System.SetSystemTime',
    index=1,
    containing_service=None,
    input_type=_TIMESTAMPREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetCountryCode',
    full_name='api.blk.System.SetCountryCode',
    index=2,
    containing_service=None,
    input_type=_COUNTRYCODEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUptime',
    full_name='api.blk.System.GetUptime',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_duration__pb2._DURATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Reboot',
    full_name='api.blk.System.Reboot',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='api.blk.System.Shutdown',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEM)

DESCRIPTOR.services_by_name['System'] = _SYSTEM

# @@protoc_insertion_point(module_scope)
