# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_select_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_JobSelect(object):
    def setupUi(self, frm_JobSelect):
        frm_JobSelect.setObjectName("frm_JobSelect")
        frm_JobSelect.resize(900, 659)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(frm_JobSelect)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(frm_JobSelect)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left: 5px")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 54))
        self.widget_6.setMaximumSize(QtCore.QSize(540, 54))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-radius: 0px; ")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnSearchProject = QtWidgets.QPushButton(self.widget_5)
        self.btnSearchProject.setMinimumSize(QtCore.QSize(40, 40))
        self.btnSearchProject.setMaximumSize(QtCore.QSize(40, 40))
        self.btnSearchProject.setStyleSheet(" border: none;\n"
"")
        self.btnSearchProject.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/search-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearchProject.setIcon(icon)
        self.btnSearchProject.setObjectName("btnSearchProject")
        self.horizontalLayout_3.addWidget(self.btnSearchProject)
        self.txtSearchProject = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.txtSearchProject.setFont(font)
        self.txtSearchProject.setStyleSheet("border: none;")
        self.txtSearchProject.setObjectName("txtSearchProject")
        self.horizontalLayout_3.addWidget(self.txtSearchProject)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_6)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_7.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("padding-left: 5px")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget_7 = QtWidgets.QWidget(self.frame_2)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 54))
        self.widget_7.setMaximumSize(QtCore.QSize(540, 54))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-radius: 0px; ")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSearchProject_2 = QtWidgets.QPushButton(self.widget_8)
        self.btnSearchProject_2.setMinimumSize(QtCore.QSize(40, 40))
        self.btnSearchProject_2.setMaximumSize(QtCore.QSize(40, 40))
        self.btnSearchProject_2.setStyleSheet(" border: none;\n"
"")
        self.btnSearchProject_2.setText("")
        self.btnSearchProject_2.setIcon(icon)
        self.btnSearchProject_2.setObjectName("btnSearchProject_2")
        self.horizontalLayout_4.addWidget(self.btnSearchProject_2)
        self.txtSearchJob = QtWidgets.QLineEdit(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.txtSearchJob.setFont(font)
        self.txtSearchJob.setStyleSheet("border: none;")
        self.txtSearchJob.setObjectName("txtSearchJob")
        self.horizontalLayout_4.addWidget(self.txtSearchJob)
        self.horizontalLayout_6.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.widget_3)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 54))
        self.btnAdd.setMaximumSize(QtCore.QSize(162, 54))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-31-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("padding-left: 5px")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_3.addWidget(self.listWidget_3)
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setMinimumSize(QtCore.QSize(54, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRemove = QtWidgets.QPushButton(self.widget_2)
        self.btnRemove.setMinimumSize(QtCore.QSize(0, 54))
        self.btnRemove.setMaximumSize(QtCore.QSize(162, 54))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-96-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon2)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(frm_JobSelect)
        QtCore.QMetaObject.connectSlotsByName(frm_JobSelect)

    def retranslateUi(self, frm_JobSelect):
        _translate = QtCore.QCoreApplication.translate
        frm_JobSelect.setWindowTitle(_translate("frm_JobSelect", "Form"))
        self.label.setText(_translate("frm_JobSelect", "Project List"))
        self.label_2.setText(_translate("frm_JobSelect", "Job List"))
        self.label_3.setText(_translate("frm_JobSelect", "Active Work Orders"))
from ui import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_JobSelect = QtWidgets.QWidget()
    ui = Ui_frm_JobSelect()
    ui.setupUi(frm_JobSelect)
    frm_JobSelect.show()
    sys.exit(app.exec_())
