# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pps.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setWindowModality(QtCore.Qt.NonModal)
        Frame.resize(924, 966)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(0, 0))
        Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Frame.setBaseSize(QtCore.QSize(960, 600))
        Frame.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_main.sizePolicy().hasHeightForWidth())
        self.tab_main.setSizePolicy(sizePolicy)
        self.tab_main.setObjectName("tab_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cloudFrame = QtWidgets.QFrame(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloudFrame.sizePolicy().hasHeightForWidth())
        self.cloudFrame.setSizePolicy(sizePolicy)
        self.cloudFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.cloudFrame.setToolTip("")
        self.cloudFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cloudFrame.setObjectName("cloudFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cloudFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.cloudFrame)
        self.frame_3 = QtWidgets.QFrame(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.btnPreScan = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPreScan.sizePolicy().hasHeightForWidth())
        self.btnPreScan.setSizePolicy(sizePolicy)
        self.btnPreScan.setMinimumSize(QtCore.QSize(0, 100))
        self.btnPreScan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnPreScan.setBaseSize(QtCore.QSize(0, 200))
        self.btnPreScan.setObjectName("btnPreScan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btnPreScan)
        self.logoLabel = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMaximumSize(QtCore.QSize(150, 50))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("jacon_logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.logoLabel)
        self.btnPostScan = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPostScan.sizePolicy().hasHeightForWidth())
        self.btnPostScan.setSizePolicy(sizePolicy)
        self.btnPostScan.setMinimumSize(QtCore.QSize(0, 100))
        self.btnPostScan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnPostScan.setBaseSize(QtCore.QSize(0, 200))
        self.btnPostScan.setObjectName("btnPostScan")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnPostScan)
        self.btnCompare = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCompare.sizePolicy().hasHeightForWidth())
        self.btnCompare.setSizePolicy(sizePolicy)
        self.btnCompare.setMinimumSize(QtCore.QSize(0, 100))
        self.btnCompare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnCompare.setBaseSize(QtCore.QSize(0, 200))
        self.btnCompare.setObjectName("btnCompare")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnCompare)
        self.btnCancel = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 100))
        self.btnCancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnCancel.setBaseSize(QtCore.QSize(0, 200))
        self.btnCancel.setAutoFillBackground(False)
        self.btnCancel.setObjectName("btnCancel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnCancel)
        self.btnOpenScanner = QtWidgets.QPushButton(self.frame_3)
        self.btnOpenScanner.setMinimumSize(QtCore.QSize(0, 100))
        self.btnOpenScanner.setObjectName("btnOpenScanner")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnOpenScanner)
        self.btnCloseScanner = QtWidgets.QPushButton(self.frame_3)
        self.btnCloseScanner.setMinimumSize(QtCore.QSize(0, 100))
        self.btnCloseScanner.setObjectName("btnCloseScanner")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btnCloseScanner)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 100))
        self.btnStop.setObjectName("btnStop")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btnStop)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.tabWidget.addTab(self.tab_setting, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.btnPreScan.setText(_translate("Frame", "Prescan"))
        self.btnPostScan.setText(_translate("Frame", "Postscan"))
        self.btnCompare.setText(_translate("Frame", "Compare"))
        self.btnCancel.setText(_translate("Frame", "Cancel"))
        self.btnOpenScanner.setText(_translate("Frame", "Open Scanner"))
        self.btnCloseScanner.setText(_translate("Frame", "Close Scanner"))
        self.btnStop.setText(_translate("Frame", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("Frame", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), _translate("Frame", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
