# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_page.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting_page(object):
    def setupUi(self, setting_page):
        setting_page.setObjectName("setting_page")
        setting_page.resize(450, 550)
        setting_page.setMinimumSize(QtCore.QSize(0, 400))
        setting_page.setMaximumSize(QtCore.QSize(16777215, 700))
        setting_page.setStyleSheet("QPushButton {\n"
"        background-color: #3498db;  /* màu nền */\n"
"        color: balck;               /* màu chữ */\n"
"        border: 1px solid #2980b9;  /* viền */\n"
"        padding: 5px 25px 5px 25px;          /* padding */\n"
"        margin: 5px 5px 5px 5px;\n"
"\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #2e86c1;  /* màu khi nhấn */\n"
"    }\n"
"\n"
"")
        self.vboxlayout = QtWidgets.QVBoxLayout(setting_page)
        self.vboxlayout.setObjectName("vboxlayout")
        self.widget = QtWidgets.QWidget(setting_page)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.txtHousingOpenFast = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingOpenFast.setObjectName("txtHousingOpenFast")
        self.gridLayout_2.addWidget(self.txtHousingOpenFast, 1, 4, 1, 1)
        self.txtHousingOpenMedium = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingOpenMedium.setObjectName("txtHousingOpenMedium")
        self.gridLayout_2.addWidget(self.txtHousingOpenMedium, 1, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 8, 1, 1)
        self.txtHousingOpenSlow = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingOpenSlow.setObjectName("txtHousingOpenSlow")
        self.gridLayout_2.addWidget(self.txtHousingOpenSlow, 1, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.txtHousingCloseSlow_2 = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingCloseSlow_2.setObjectName("txtHousingCloseSlow_2")
        self.gridLayout_2.addWidget(self.txtHousingCloseSlow_2, 2, 8, 1, 1)
        self.txtHousingCloseMedium = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingCloseMedium.setObjectName("txtHousingCloseMedium")
        self.gridLayout_2.addWidget(self.txtHousingCloseMedium, 2, 7, 1, 1)
        self.txtHousingCloseFast = QtWidgets.QLineEdit(self.widget_2)
        self.txtHousingCloseFast.setObjectName("txtHousingCloseFast")
        self.gridLayout_2.addWidget(self.txtHousingCloseFast, 2, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.txtHousingStartPosition = QtWidgets.QLineEdit(self.widget_3)
        self.txtHousingStartPosition.setObjectName("txtHousingStartPosition")
        self.gridLayout_3.addWidget(self.txtHousingStartPosition, 0, 2, 1, 1)
        self.txtHousingEndPosition = QtWidgets.QLineEdit(self.widget_3)
        self.txtHousingEndPosition.setObjectName("txtHousingEndPosition")
        self.gridLayout_3.addWidget(self.txtHousingEndPosition, 1, 2, 1, 1)
        self.txtHousingClosedPosition = QtWidgets.QLineEdit(self.widget_3)
        self.txtHousingClosedPosition.setObjectName("txtHousingClosedPosition")
        self.gridLayout_3.addWidget(self.txtHousingClosedPosition, 2, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_49 = QtWidgets.QLabel(self.widget_5)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_5)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget_5)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.txtTunnelMinBoundX = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMinBoundX.setObjectName("txtTunnelMinBoundX")
        self.gridLayout_5.addWidget(self.txtTunnelMinBoundX, 1, 1, 1, 1)
        self.txtTunnelMinBoundY = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMinBoundY.setObjectName("txtTunnelMinBoundY")
        self.gridLayout_5.addWidget(self.txtTunnelMinBoundY, 1, 2, 1, 1)
        self.txtTunnelMinBoundZ = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMinBoundZ.setObjectName("txtTunnelMinBoundZ")
        self.gridLayout_5.addWidget(self.txtTunnelMinBoundZ, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 0, 1, 1)
        self.txtTunnelMaxBoundX = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMaxBoundX.setObjectName("txtTunnelMaxBoundX")
        self.gridLayout_5.addWidget(self.txtTunnelMaxBoundX, 2, 1, 1, 1)
        self.txtTunnelMaxBoundY = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMaxBoundY.setObjectName("txtTunnelMaxBoundY")
        self.gridLayout_5.addWidget(self.txtTunnelMaxBoundY, 2, 2, 1, 1)
        self.txtTunnelMaxBoundZ = QtWidgets.QLineEdit(self.widget_5)
        self.txtTunnelMaxBoundZ.setObjectName("txtTunnelMaxBoundZ")
        self.gridLayout_5.addWidget(self.txtTunnelMaxBoundZ, 2, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnUpdateHousingParam = QtWidgets.QPushButton(self.widget_4)
        self.btnUpdateHousingParam.setObjectName("btnUpdateHousingParam")
        self.horizontalLayout.addWidget(self.btnUpdateHousingParam)
        self.btnCancelHousingParam = QtWidgets.QPushButton(self.widget_4)
        self.btnCancelHousingParam.setObjectName("btnCancelHousingParam")
        self.horizontalLayout.addWidget(self.btnCancelHousingParam)
        self.verticalLayout_2.addWidget(self.widget_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.vboxlayout.addWidget(self.widget)

        self.retranslateUi(setting_page)
        QtCore.QMetaObject.connectSlotsByName(setting_page)

    def retranslateUi(self, setting_page):
        _translate = QtCore.QCoreApplication.translate
        setting_page.setWindowTitle(_translate("setting_page", "Form"))
        self.groupBox.setTitle(_translate("setting_page", "Housing parameters"))
        self.label_10.setText(_translate("setting_page", "Medium"))
        self.label_8.setText(_translate("setting_page", "Housing close speed (Hz)"))
        self.label_9.setText(_translate("setting_page", "Fast"))
        self.label_11.setText(_translate("setting_page", "Slow"))
        self.label_7.setText(_translate("setting_page", "Housing open speed (Hz)"))
        self.label_14.setText(_translate("setting_page", "Encoder at fully closed housing position"))
        self.label_12.setText(_translate("setting_page", "Housing start scan angle (deg)"))
        self.label_13.setText(_translate("setting_page", "Housing end scan angle (deg)"))
        self.groupBox_2.setTitle(_translate("setting_page", "Tunnel bounding box"))
        self.label_49.setText(_translate("setting_page", "X"))
        self.label_51.setText(_translate("setting_page", "Y"))
        self.label_50.setText(_translate("setting_page", "Z"))
        self.label_15.setText(_translate("setting_page", "Min bound"))
        self.label_16.setText(_translate("setting_page", "Max bound"))
        self.btnUpdateHousingParam.setText(_translate("setting_page", "Update"))
        self.btnCancelHousingParam.setText(_translate("setting_page", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setting_page = QtWidgets.QWidget()
    ui = Ui_setting_page()
    ui.setupUi(setting_page)
    setting_page.show()
    sys.exit(app.exec_())
