# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sitesetting_page.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSiteSetting(object):
    def setupUi(self, frmJobSetting):
        frmJobSetting.setObjectName("frmJobSetting")
        frmJobSetting.resize(844, 579)
        frmJobSetting.setStyleSheet("*{\n"
"color: black;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(frmJobSetting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_9 = QtWidgets.QWidget(frmJobSetting)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        self.widget_4.setEnabled(True)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setContentsMargins(4, 1, 4, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.txtJobNumber_3 = QtWidgets.QLineEdit(self.widget_7)
        self.txtJobNumber_3.setMinimumSize(QtCore.QSize(150, 0))
        self.txtJobNumber_3.setObjectName("txtJobNumber_3")
        self.horizontalLayout_5.addWidget(self.txtJobNumber_3)
        self.btnCreateSite = QtWidgets.QPushButton(self.widget_7)
        self.btnCreateSite.setObjectName("btnCreateSite")
        self.horizontalLayout_5.addWidget(self.btnCreateSite)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 6)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_JobList_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_JobList_3.setObjectName("widget_JobList_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_JobList_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lstSites = QtWidgets.QListWidget(self.widget_JobList_3)
        self.lstSites.setObjectName("lstSites")
        self.gridLayout_4.addWidget(self.lstSites, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_JobList_3)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.txtSearchSite = QtWidgets.QLineEdit(self.widget_8)
        self.txtSearchSite.setMinimumSize(QtCore.QSize(150, 0))
        self.txtSearchSite.setObjectName("txtSearchSite")
        self.horizontalLayout_6.addWidget(self.txtSearchSite)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 6)
        self.gridLayout_4.addWidget(self.widget_8, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_JobList_3)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(self.widget_9)
        self.widget.setEnabled(False)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widget_11)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.txtSiteName = QtWidgets.QLabel(self.widget_11)
        self.txtSiteName.setObjectName("txtSiteName")
        self.horizontalLayout_9.addWidget(self.txtSiteName)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_11)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtJobNumber = QtWidgets.QLineEdit(self.widget_2)
        self.txtJobNumber.setMinimumSize(QtCore.QSize(150, 0))
        self.txtJobNumber.setObjectName("txtJobNumber")
        self.horizontalLayout.addWidget(self.txtJobNumber)
        self.btnCreateJob = QtWidgets.QPushButton(self.widget_2)
        self.btnCreateJob.setObjectName("btnCreateJob")
        self.horizontalLayout.addWidget(self.btnCreateJob)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 6)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_JobList = QtWidgets.QWidget(self.widget)
        self.widget_JobList.setObjectName("widget_JobList")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_JobList)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_JobList)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtFilter = QtWidgets.QLineEdit(self.widget_3)
        self.txtFilter.setMinimumSize(QtCore.QSize(150, 0))
        self.txtFilter.setObjectName("txtFilter")
        self.horizontalLayout_2.addWidget(self.txtFilter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 6)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.lstJobnumber = QtWidgets.QListWidget(self.widget_JobList)
        self.lstJobnumber.setObjectName("lstJobnumber")
        self.gridLayout_2.addWidget(self.lstJobnumber, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_JobList)
        self.horizontalLayout_7.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(frmJobSetting)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnClose = QtWidgets.QPushButton(self.widget_10)
        self.btnClose.setMinimumSize(QtCore.QSize(100, 40))
        self.btnClose.setMaximumSize(QtCore.QSize(100, 30))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_8.addWidget(self.btnClose)
        self.verticalLayout_4.addWidget(self.widget_10)

        self.retranslateUi(frmJobSetting)
        self.btnClose.released.connect(frmJobSetting.close)
        QtCore.QMetaObject.connectSlotsByName(frmJobSetting)

    def retranslateUi(self, frmJobSetting):
        _translate = QtCore.QCoreApplication.translate
        frmJobSetting.setWindowTitle(_translate("frmJobSetting", "Form"))
        self.label_5.setText(_translate("frmJobSetting", "Site Name"))
        self.btnCreateSite.setText(_translate("frmJobSetting", "Create"))
        self.label_6.setText(_translate("frmJobSetting", "Search:"))
        self.label_7.setText(_translate("frmJobSetting", "Site Name"))
        self.txtSiteName.setText(_translate("frmJobSetting", "Unknown"))
        self.label.setText(_translate("frmJobSetting", "Job number"))
        self.btnCreateJob.setText(_translate("frmJobSetting", "Create"))
        self.label_2.setText(_translate("frmJobSetting", "Search:"))
        self.btnClose.setText(_translate("frmJobSetting", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmJobSetting = QtWidgets.QWidget()
    ui = Ui_frmSiteSetting()
    ui.setupUi(frmJobSetting)
    frmJobSetting.show()
    sys.exit(app.exec_())
