# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_number_keyboard(object):
    def setupUi(self, number_keyboard):
        number_keyboard.setObjectName("number_keyboard")
        number_keyboard.resize(688, 234)
        font = QtGui.QFont()
        font.setPointSize(20)
        number_keyboard.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(number_keyboard)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(number_keyboard)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1.setObjectName("btn_1")
        self.horizontalLayout.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout.addWidget(self.btn_3)
        self.btn_4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4.setObjectName("btn_4")
        self.horizontalLayout.addWidget(self.btn_4)
        self.btn_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5.setObjectName("btn_5")
        self.horizontalLayout.addWidget(self.btn_5)
        self.btn_6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6.setObjectName("btn_6")
        self.horizontalLayout.addWidget(self.btn_6)
        self.btn_7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7.setObjectName("btn_7")
        self.horizontalLayout.addWidget(self.btn_7)
        self.btn_8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8.setObjectName("btn_8")
        self.horizontalLayout.addWidget(self.btn_8)
        self.btn_9 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_9.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_9.setObjectName("btn_9")
        self.horizontalLayout.addWidget(self.btn_9)
        self.btn_0 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        self.btn_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0.setObjectName("btn_0")
        self.horizontalLayout.addWidget(self.btn_0)
        self.btn_Minus = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Minus.sizePolicy().hasHeightForWidth())
        self.btn_Minus.setSizePolicy(sizePolicy)
        self.btn_Minus.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Minus.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Minus.setObjectName("btn_Minus")
        self.horizontalLayout.addWidget(self.btn_Minus)
        self.btn_Backspace = QtWidgets.QPushButton(self.widget)
        self.btn_Backspace.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Backspace.setMaximumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Backspace.setIcon(icon)
        self.btn_Backspace.setIconSize(QtCore.QSize(40, 40))
        self.btn_Backspace.setObjectName("btn_Backspace")
        self.horizontalLayout.addWidget(self.btn_Backspace)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_q = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_q.sizePolicy().hasHeightForWidth())
        self.btn_q.setSizePolicy(sizePolicy)
        self.btn_q.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_q.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_q.setObjectName("btn_q")
        self.horizontalLayout_2.addWidget(self.btn_q)
        self.btn_w = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_w.sizePolicy().hasHeightForWidth())
        self.btn_w.setSizePolicy(sizePolicy)
        self.btn_w.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_w.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_w.setObjectName("btn_w")
        self.horizontalLayout_2.addWidget(self.btn_w)
        self.btn_e = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_e.sizePolicy().hasHeightForWidth())
        self.btn_e.setSizePolicy(sizePolicy)
        self.btn_e.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_e.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_e.setObjectName("btn_e")
        self.horizontalLayout_2.addWidget(self.btn_e)
        self.btn_r = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_r.sizePolicy().hasHeightForWidth())
        self.btn_r.setSizePolicy(sizePolicy)
        self.btn_r.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_r.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_r.setObjectName("btn_r")
        self.horizontalLayout_2.addWidget(self.btn_r)
        self.btn_t = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_t.sizePolicy().hasHeightForWidth())
        self.btn_t.setSizePolicy(sizePolicy)
        self.btn_t.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_t.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_t.setObjectName("btn_t")
        self.horizontalLayout_2.addWidget(self.btn_t)
        self.btn_y = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_y.sizePolicy().hasHeightForWidth())
        self.btn_y.setSizePolicy(sizePolicy)
        self.btn_y.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_y.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_y.setObjectName("btn_y")
        self.horizontalLayout_2.addWidget(self.btn_y)
        self.btn_u = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_u.sizePolicy().hasHeightForWidth())
        self.btn_u.setSizePolicy(sizePolicy)
        self.btn_u.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_u.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_u.setObjectName("btn_u")
        self.horizontalLayout_2.addWidget(self.btn_u)
        self.btn_i = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_i.sizePolicy().hasHeightForWidth())
        self.btn_i.setSizePolicy(sizePolicy)
        self.btn_i.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_i.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_i.setObjectName("btn_i")
        self.horizontalLayout_2.addWidget(self.btn_i)
        self.btn_o = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_o.sizePolicy().hasHeightForWidth())
        self.btn_o.setSizePolicy(sizePolicy)
        self.btn_o.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_o.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_o.setObjectName("btn_o")
        self.horizontalLayout_2.addWidget(self.btn_o)
        self.btn_p = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_p.sizePolicy().hasHeightForWidth())
        self.btn_p.setSizePolicy(sizePolicy)
        self.btn_p.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_p.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_p.setObjectName("btn_p")
        self.horizontalLayout_2.addWidget(self.btn_p)
        self.btn_Dot = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Dot.sizePolicy().hasHeightForWidth())
        self.btn_Dot.setSizePolicy(sizePolicy)
        self.btn_Dot.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Dot.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_Dot.setObjectName("btn_Dot")
        self.horizontalLayout_2.addWidget(self.btn_Dot)
        self.btn_Hide = QtWidgets.QPushButton(self.widget_2)
        self.btn_Hide.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_Hide.setMaximumSize(QtCore.QSize(50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/hide-keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Hide.setIcon(icon1)
        self.btn_Hide.setIconSize(QtCore.QSize(40, 40))
        self.btn_Hide.setObjectName("btn_Hide")
        self.horizontalLayout_2.addWidget(self.btn_Hide)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_a = QtWidgets.QPushButton(self.widget_3)
        self.btn_a.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_a.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_a.setObjectName("btn_a")
        self.horizontalLayout_3.addWidget(self.btn_a)
        self.btn_s = QtWidgets.QPushButton(self.widget_3)
        self.btn_s.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_s.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_s.setObjectName("btn_s")
        self.horizontalLayout_3.addWidget(self.btn_s)
        self.btn_d = QtWidgets.QPushButton(self.widget_3)
        self.btn_d.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_d.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_d.setObjectName("btn_d")
        self.horizontalLayout_3.addWidget(self.btn_d)
        self.btn_f = QtWidgets.QPushButton(self.widget_3)
        self.btn_f.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_f.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_f.setObjectName("btn_f")
        self.horizontalLayout_3.addWidget(self.btn_f)
        self.btn_g = QtWidgets.QPushButton(self.widget_3)
        self.btn_g.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_g.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_g.setObjectName("btn_g")
        self.horizontalLayout_3.addWidget(self.btn_g)
        self.btn_h = QtWidgets.QPushButton(self.widget_3)
        self.btn_h.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_h.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_h.setObjectName("btn_h")
        self.horizontalLayout_3.addWidget(self.btn_h)
        self.btn_j = QtWidgets.QPushButton(self.widget_3)
        self.btn_j.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_j.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_j.setObjectName("btn_j")
        self.horizontalLayout_3.addWidget(self.btn_j)
        self.btn_k = QtWidgets.QPushButton(self.widget_3)
        self.btn_k.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_k.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_k.setObjectName("btn_k")
        self.horizontalLayout_3.addWidget(self.btn_k)
        self.btn_l = QtWidgets.QPushButton(self.widget_3)
        self.btn_l.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_l.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_l.setObjectName("btn_l")
        self.horizontalLayout_3.addWidget(self.btn_l)
        self.btn_Enter = QtWidgets.QPushButton(self.widget_3)
        self.btn_Enter.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_Enter.setMaximumSize(QtCore.QSize(150, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Enter.setIcon(icon2)
        self.btn_Enter.setIconSize(QtCore.QSize(30, 30))
        self.btn_Enter.setObjectName("btn_Enter")
        self.horizontalLayout_3.addWidget(self.btn_Enter)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_Shift = QtWidgets.QPushButton(self.widget_4)
        self.btn_Shift.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_Shift.setMaximumSize(QtCore.QSize(100, 50))
        self.btn_Shift.setObjectName("btn_Shift")
        self.horizontalLayout_4.addWidget(self.btn_Shift)
        self.btn_z = QtWidgets.QPushButton(self.widget_4)
        self.btn_z.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_z.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_z.setObjectName("btn_z")
        self.horizontalLayout_4.addWidget(self.btn_z)
        self.btn_x = QtWidgets.QPushButton(self.widget_4)
        self.btn_x.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_x.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_x.setObjectName("btn_x")
        self.horizontalLayout_4.addWidget(self.btn_x)
        self.btn_Space = QtWidgets.QPushButton(self.widget_4)
        self.btn_Space.setMinimumSize(QtCore.QSize(175, 50))
        self.btn_Space.setMaximumSize(QtCore.QSize(175, 50))
        self.btn_Space.setText("")
        self.btn_Space.setObjectName("btn_Space")
        self.horizontalLayout_4.addWidget(self.btn_Space)
        self.btn_c = QtWidgets.QPushButton(self.widget_4)
        self.btn_c.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_c.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_c.setObjectName("btn_c")
        self.horizontalLayout_4.addWidget(self.btn_c)
        self.btn_v = QtWidgets.QPushButton(self.widget_4)
        self.btn_v.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_v.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_v.setObjectName("btn_v")
        self.horizontalLayout_4.addWidget(self.btn_v)
        self.btn_b = QtWidgets.QPushButton(self.widget_4)
        self.btn_b.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_b.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_b.setObjectName("btn_b")
        self.horizontalLayout_4.addWidget(self.btn_b)
        self.btn_n = QtWidgets.QPushButton(self.widget_4)
        self.btn_n.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_n.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_n.setObjectName("btn_n")
        self.horizontalLayout_4.addWidget(self.btn_n)
        self.btn_m = QtWidgets.QPushButton(self.widget_4)
        self.btn_m.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_m.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_m.setObjectName("btn_m")
        self.horizontalLayout_4.addWidget(self.btn_m)
        self.verticalLayout.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)

        self.retranslateUi(number_keyboard)
        QtCore.QMetaObject.connectSlotsByName(number_keyboard)

    def retranslateUi(self, number_keyboard):
        _translate = QtCore.QCoreApplication.translate
        number_keyboard.setWindowTitle(_translate("number_keyboard", "Dialog"))
        self.btn_1.setText(_translate("number_keyboard", "1"))
        self.btn_2.setText(_translate("number_keyboard", "2"))
        self.btn_3.setText(_translate("number_keyboard", "3"))
        self.btn_4.setText(_translate("number_keyboard", "4"))
        self.btn_5.setText(_translate("number_keyboard", "5"))
        self.btn_6.setText(_translate("number_keyboard", "6"))
        self.btn_7.setText(_translate("number_keyboard", "7"))
        self.btn_8.setText(_translate("number_keyboard", "8"))
        self.btn_9.setText(_translate("number_keyboard", "9"))
        self.btn_0.setText(_translate("number_keyboard", "0"))
        self.btn_Minus.setText(_translate("number_keyboard", "-"))
        self.btn_q.setText(_translate("number_keyboard", "Q"))
        self.btn_w.setText(_translate("number_keyboard", "W"))
        self.btn_e.setText(_translate("number_keyboard", "E"))
        self.btn_r.setText(_translate("number_keyboard", "R"))
        self.btn_t.setText(_translate("number_keyboard", "T"))
        self.btn_y.setText(_translate("number_keyboard", "Y"))
        self.btn_u.setText(_translate("number_keyboard", "U"))
        self.btn_i.setText(_translate("number_keyboard", "I"))
        self.btn_o.setText(_translate("number_keyboard", "O"))
        self.btn_p.setText(_translate("number_keyboard", "P"))
        self.btn_Dot.setText(_translate("number_keyboard", "."))
        self.btn_a.setText(_translate("number_keyboard", "A"))
        self.btn_s.setText(_translate("number_keyboard", "S"))
        self.btn_d.setText(_translate("number_keyboard", "D"))
        self.btn_f.setText(_translate("number_keyboard", "F"))
        self.btn_g.setText(_translate("number_keyboard", "G"))
        self.btn_h.setText(_translate("number_keyboard", "H"))
        self.btn_j.setText(_translate("number_keyboard", "J"))
        self.btn_k.setText(_translate("number_keyboard", "K"))
        self.btn_l.setText(_translate("number_keyboard", "L"))
        self.btn_Shift.setText(_translate("number_keyboard", "Shift"))
        self.btn_z.setText(_translate("number_keyboard", "Z"))
        self.btn_x.setText(_translate("number_keyboard", "X"))
        self.btn_c.setText(_translate("number_keyboard", "C"))
        self.btn_v.setText(_translate("number_keyboard", "V"))
        self.btn_b.setText(_translate("number_keyboard", "B"))
        self.btn_n.setText(_translate("number_keyboard", "N"))
        self.btn_m.setText(_translate("number_keyboard", "M"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    number_keyboard = QtWidgets.QDialog()
    ui = Ui_number_keyboard()
    ui.setupUi(number_keyboard)
    number_keyboard.show()
    sys.exit(app.exec_())
