# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './number_keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_number_keyboard(object):
    def setupUi(self, number_keyboard):
        number_keyboard.setObjectName("number_keyboard")
        number_keyboard.resize(340, 346)
        font = QtGui.QFont()
        font.setPointSize(20)
        number_keyboard.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(number_keyboard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(number_keyboard)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_7 = QtWidgets.QPushButton(self.widget)
        self.btn_7.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_7.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 0, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.widget)
        self.btn_8.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_8.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 0, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.widget)
        self.btn_9.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_9.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 0, 2, 1, 1)
        self.btn_Backspace = QtWidgets.QPushButton(self.widget)
        self.btn_Backspace.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_Backspace.setMaximumSize(QtCore.QSize(70, 70))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Backspace.setIcon(icon)
        self.btn_Backspace.setIconSize(QtCore.QSize(40, 40))
        self.btn_Backspace.setObjectName("btn_Backspace")
        self.gridLayout.addWidget(self.btn_Backspace, 0, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.widget)
        self.btn_4.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_4.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.widget)
        self.btn_5.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_5.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.widget)
        self.btn_6.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_6.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_15.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 1, 3, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.widget)
        self.btn_1.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_1.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 2, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.widget)
        self.btn_2.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_2.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        self.btn_3.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_3.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 2, 2, 1, 1)
        self.btn_Enter = QtWidgets.QPushButton(self.widget)
        self.btn_Enter.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_Enter.setMaximumSize(QtCore.QSize(70, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Enter.setIcon(icon1)
        self.btn_Enter.setIconSize(QtCore.QSize(30, 30))
        self.btn_Enter.setObjectName("btn_Enter")
        self.gridLayout.addWidget(self.btn_Enter, 2, 3, 1, 1)
        self.btn_Minus = QtWidgets.QPushButton(self.widget)
        self.btn_Minus.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_Minus.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_Minus.setObjectName("btn_Minus")
        self.gridLayout.addWidget(self.btn_Minus, 3, 0, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.widget)
        self.btn_0.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_0.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 3, 1, 1, 1)
        self.btn_Dot = QtWidgets.QPushButton(self.widget)
        self.btn_Dot.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_Dot.setMaximumSize(QtCore.QSize(70, 70))
        self.btn_Dot.setObjectName("btn_Dot")
        self.gridLayout.addWidget(self.btn_Dot, 3, 2, 1, 1)
        self.btn_Hide = QtWidgets.QPushButton(self.widget)
        self.btn_Hide.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_Hide.setMaximumSize(QtCore.QSize(70, 70))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/hide-keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Hide.setIcon(icon2)
        self.btn_Hide.setIconSize(QtCore.QSize(40, 40))
        self.btn_Hide.setObjectName("btn_Hide")
        self.gridLayout.addWidget(self.btn_Hide, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(number_keyboard)
        QtCore.QMetaObject.connectSlotsByName(number_keyboard)

    def retranslateUi(self, number_keyboard):
        _translate = QtCore.QCoreApplication.translate
        number_keyboard.setWindowTitle(_translate("number_keyboard", "Dialog"))
        self.btn_7.setText(_translate("number_keyboard", "7"))
        self.btn_8.setText(_translate("number_keyboard", "8"))
        self.btn_9.setText(_translate("number_keyboard", "9"))
        self.btn_4.setText(_translate("number_keyboard", "4"))
        self.btn_5.setText(_translate("number_keyboard", "5"))
        self.btn_6.setText(_translate("number_keyboard", "6"))
        self.btn_1.setText(_translate("number_keyboard", "1"))
        self.btn_2.setText(_translate("number_keyboard", "2"))
        self.btn_3.setText(_translate("number_keyboard", "3"))
        self.btn_Minus.setText(_translate("number_keyboard", "-"))
        self.btn_0.setText(_translate("number_keyboard", "0"))
        self.btn_Dot.setText(_translate("number_keyboard", "."))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    number_keyboard = QtWidgets.QDialog()
    ui = Ui_number_keyboard()
    ui.setupUi(number_keyboard)
    number_keyboard.show()
    sys.exit(app.exec_())
