#!/bin/bash

# export PYTHONPATH=/mnt/c/work/projects/intelijet_v2/leica_blkarc/src/python_sample_wrapper/ros_sample_wrapper/ros_blkarc_driver/src:$PYTHONPATH
# Phai build bang catkin_build
# va activate moi truong cung nhu setup ROS env

# cd /mnt/c/work/projects/intelijet_v2/leica_blkarc || exit

# source .venv/bin/activate
# source /opt/ros/noetic/setup.bash
# source devel/setup.bash

# # export PYTHONPATH=$(pwd)/src/python_sample_wrapper:/opt/ros/noetic/lib/python3/dist-packages
# # export ROS_PACKAGE_PATH=$(pwd)/src/python_sample_wrapper/ros_sample_wrapper:$ROS_PACKAGE_PATH

# rosrun ros_blkarc_driver blkarc_ros_node
