#!/usr/bin/env python3

import rospy

from ros_blkarc_driver  import BLKARCROSWrapper

if __name__ == "__main__":
    try:
        rospy.init_node(name="blkarc_ros_wrapper", log_level=rospy.INFO)
        blkarc_ros_wrapper = BLKARCROSWrapper()
        rospy.on_shutdown(blkarc_ros_wrapper.close)
        rospy.spin()
    except rospy.ROSInterruptException:
        rospy.loginfo("ROS node interrupted.")
    except Exception as e:
        rospy.logerr(f"Unhandled exception: {e}")
